### PR TITLE
Merge prints into single system-out

### LINKED ISSUE #1: Multiple system outs in XML output
According to JUnit v4 XSD, having multiple `system-out` for a test-case is invalid.

Example to invalid XML:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite errors="0" failures="0" tests="6" skipped="0" name="test.ipsums" timestamp="2017-02-21T15:02:29">
    <properties>
      <property name="platform" value="dartium" />
    </properties>
    <testcase classname="ipsum" name="habla hable" time="0.015" />
    <system-out>Muhaha</system-out>
    <system-out>Another line</system-out>
  </testsuite>
</testsuites>
```

The converter should merge the `print`s of that belong to the same testsuite.

### PR DESCRIPTION
**Pull request by daniel-v**
This change merges multiple `print`s into a single xml `system-out` xml element. Prints are separated with `\n`.
As per JUnit 4 XSD, the generated output was invalid.

Also removed lock file and added it to .gitignore.

fixes #1

### CODE REVIEW

**Comment by rspilker** [comment]
Hi Daniel,

Thanks for the pull request.

Do you use junitreport as a library or as an application? I did add the lock file on purpose, because for applications, that's what you should do. See [the gitignore template](https://github.com/github/gitignore/blob/master/Dart.gitignore#L32).

Finally, can you please add you name the the AUTHORS file, so we are legally covered?

**Comment by daniel-v** [comment]
As an application. 
I'll revert the first 2 commits and do the other changes you requested.

**Comment by daniel-v** [comment]
I've added myself to the AUTHORS file. Also found another place authors were references, in pubspec.yaml. I added myself there too. (Need me to remove myself from there?)

**Comment by rspilker** [comment]
I've cleaned up the history a bit, using `git rebase -i`, to remove the pubspec.lock file removal and reintroduction from history.

**Comment by rspilker** [comment]
You should not be listed in the `pubspec.yaml`

**Pull request closed without merging**
